extends: "@wfcd/eslint-config/typescript"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
  babelOptions:
    plugins:
      - "@typescript-eslint/eslint-plugin"
      - "@babel/plugin-transform-class-properties"
      - "@babel/plugin-transform-private-methods"
rules:
  # conflicts w/ prettier, should probably upstream this
  '@typescript-eslint/comma-dangle': 'off'
  'import/extensions': off
  '@typescript-eslint/no-explicit-any': off