pull_request_rules:
  - name: Automerge wfcd-bot-boi PRs that Pass
    conditions:
      - "approved-reviews-by=@WFCD/node-libraries"
      - "author=wfcd-bot-boi"
      - "status-success=Actions / Lint (15.x) (pull_request)"
      - "status-success=Actions / Test (15.x) (pull_request)"
      - "status-success=Actions / Test (14.x) (pull_request)"
      - "status-success=Actions / Test (13.x) (pull_request)"
      - "status-success=Actions / Test (12.x) (pull_request)"
      - "status-success=Actions / Test (11.x) (pull_request)"
      - "status-success=WIP"
      - "status-success=codeclimate"
      - "status-success=security/snyk (TobiTenno)"
    actions:
      merge:
        method: squash
  - name: Automerge snyk PRs that Pass
    conditions:
      - "approved-reviews-by=@WFCD/node-libraries"
      - "author=snyk-bot"
      - "status-success=Actions / Lint (15.x) (pull_request)"
      - "status-success=Actions / Test (15.x) (pull_request)"
      - "status-success=Actions / Test (14.x) (pull_request)"
      - "status-success=Actions / Test (13.x) (pull_request)"
      - "status-success=Actions / Test (12.x) (pull_request)"
      - "status-success=Actions / Test (11.x) (pull_request)"
      - "status-success=WIP"
      - "status-success=codeclimate"
      - "status-success=security/snyk (TobiTenno)"
    actions:
      merge:
        method: squash
