pull_request_rules:
  - name: Automerge wfcd-bot-boi PRs that Pass
    conditions:
      - "approved-reviews-by=@WFCD/node-libraries"
      - "author=wfcd-bot-boi"
      - "status-success=Travis CI - Branch"
      - "status-success=Travis CI - Pull Request"
      - "status-success=WIP"
      - "status-success=codeclimate"
      - "status-success=security/snyk (TobiTenno)"
    actions:
      merge:
        method: squash
        strict: true
        strict_method: rebase
  - name: Automerge snyk PRs that Pass
    conditions:
      - "approved-reviews-by=@WFCD/node-libraries"
      - "author=snyk-bot"
      - "status-success=Travis CI - Branch"
      - "status-success=Travis CI - Pull Request"
      - "status-success=WIP"
      - "status-success=codeclimate"
      - "status-success=security/snyk (TobiTenno)"
    actions:
      merge:
        method: squash
        strict: true
        strict_method: rebase
