language: node_js
os: linux
dist: bionic
cache:
  timeout: 3
  directories:
    - ~/.npm

notifications:
  email: false
node_js:
  - 'node'
  - 'lts/*'

stages:
  - lint
  - test
  - release

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm test
    - stage: release
      node_js: node
      deploy:
        provider: script
        cleanuo: false
        script: npx semantic-release
