language: node_js
os: linux
dist: bionic
cache:
  timeout: 3
  directories:
    - ~/.npm

notifications:
  email: false
node_js:
  - 'node'
  - 'lts/*'
  - 13
  - 12
  - 11
  - 10
  - 9
  - 8

stages:
  - lint
  - test
  - name: release
    if: branch = master && type NOT IN (pull_request)

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: release
      node_js: node
      deploy:
        provider: script
        cleanuo: false
        script: npx semantic-release
