append_commit_message: false
commit_message: 'fix(%language%): new translations in %original_file_name%'
pull_request_title: 'fix(l10n): new translations'

files:
  - source: /data/*.json
    translation: /data/%two_letters_code%/%original_file_name%
